### ISSUE TITLE
Port in progress? TD-API will be deactivated May 10th 2024, and registration is apparently open for Schwab API

### ISSUE THREAD

**Issue by spitrespectable** [alexgolec/schwab-py#1]
Hi!  Thanks for your work on TD-API!

Are you signing up for the Schwab API and have the time to port to it?   If so, people would probably sign up for your patreon if you put one up.

If you don't have time/interest, that would be good to know, so folks can make other plans / branch.

I haven't transitioned to Schwab yet, but saw https://www.reddit.com/r/tdameritrade/comments/1bqv30q/api_update/

in case it gets deleted or spam filtered

> I received email today indicating the Schwab API is now 'open'. Key is:

> Existing TD Ameritrade API endpoints, while currently still available, will be disabled after market close on May 10, 2024.

> Currently you need a Schwab account and given I can't create a Schwab login until April 9, this basically means I have 30 days to transition my existing applications to Schwab.

> However, you can now at least read the documentation and am doing so now and will update the post. At first glance (brief review in 5 minutes), the API looks quite similar to TD, so suspecting they simply lifted the TD API (be kind, this is after 5 minutes of reading).

**Comment by alexgolec** [comment]
This port is in progress, and I'm pushing out releases as new features are added and improvements are made. Please join the discord server to follow along.
