### ISSUE TITLE
Add documented ENUMs to Quote.Fields

### ISSUE THREAD

**Issue by vandel** [alexgolec/schwab-py#109]
Update base.py class Quote to provide for reduction in excess information transmitted with every quote

    class Quote:
        class Fields(Enum):
            QUOTE = 'quote'
            FUNDAMENTAL = 'fundamental'
            REFERENCE = 'reference'
            EXTENDED = 'extended'
            REGULAR = 'regular'

I have been running with this edit for the past couple versions including 1.0 with expected performance and no observed adverse effects.

**Comment by alexgolec** [comment]
Where are these enums documented? I can't find them anywhere on the Schwab site.
