### ISSUE TITLE
Unable to pass in from_date and to_date as arguments to the get_option_chain method.  

### ISSUE THREAD

**Issue by dynoweb** [alexgolec/schwab-py#11]
**Description of Bug**
When calling get_option_chain and passing in the querry parms from_date and to_date the schwab-py library expects datetime.date and datetime.datetime.

**Code to Reproduce**
    from_date = date(2024, 4, 22)
    to_date = date(2024, 4, 23)

    response = client.get_option_chain("$SPX",
                                       strike_count=10,
                                       include_underlying_quote='true',
                                       from_date=from_date,
                                       to_date=to_date)

**Expected Behavior**
I expected to pass in those dates to restrict which option chains the API returned.

**Actual Behavior**
{
    "errors": [
        {
            "id": "f3bbb9ef-1d5b-4c99-b1f7-ba18a251524a",
            "status": "400",
            "title": "Bad Request",
            "detail": "fromDate should be of ISO DATE format: yyyy-MM-dd",
            "source": {
                "parameter": "fromDate"
            }
        },
        {
            "id": "c8396338-5237-4eb1-a54c-7cd282af097e",
            "status": "400",
            "title": "Bad Request",
            "detail": "toDate should be of ISO DATE format: yyyy-MM-dd",
            "source": {
                "parameter": "toDate"
            }
        }
    ]
}

**Error/Exception Log, If Applicable**
See here to learn how to turn on debug logging: https://tda-api.readthedocs.io/en/latest/help.html
I wasn't sure how to enable to logging for the schwab-py lib, documentation should be updated.
tda.debug.enable_bug_report_logging()

**Comment by dynoweb** [comment]
I traced through the code,  no matter what, we are passing return d.strftime('%Y-%m-%dT%H:%M:%SZ') into those date fields.  A time on an option expiration doesn't make sense anyway.  That should only be datatime.date using d.strftime('%Y-%m-%d')

**Comment by dynoweb** [comment]
I checked out the branch, created my own branch and made the changes, I've also tested this by making the call to the Schwab server and it worked as I expected.  I also tested these alternatives

from_date = date(2024, 4, 22)   # this worked
from_date = "2024-04-22"        # this returned error from the type assertion 
from_date = datetime(2024, 4, 22, 8, 30)  # this works and sends just the date portion of this datetime 

Here's the code that I used

    def _format_date(self, var_name, dt):
        '''Formats datetime objects appropriately, depending on whether they are
        naive or timezone-aware'''
        self._assert_type(var_name, dt, [self._DATE])

        if isinstance(dt, self._DATE):
            d = datetime.date(year=dt.year, month=dt.month, day=dt.day)

        return d.strftime('%Y-%m-%d')

**Comment by SkyHyperV** [comment]
This should be fixed with your PR#12

**Comment by alexgolec** [comment]
This is fixed in the latest release
