### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by tagavii** [alexgolec/schwab-py#115]
Hi Alex,
Following info might be useful to update schwab.py docs. I contacted schwab regarding the availability of "TIMESALE_EQUITY" stream and they provided following clariffications:

1. Streaming docs (like what we had for TDA) will be available soon ( end-of-May ETA)

2. "Timesale" or "Trade" stream is not a feature in their dev plan. Consistent with this clarification, when I try "stream_client.add_timesale_equity_handler", API throws this: "Service not available or temporary down".  Schwab indicated that they're open to adding timesale to their dev plan but I guess that's subject to high demand from us users. 

I added their replies below just in case. Thank you for all your work on TDA (RIP) and schwab wrappers!
PS: wasn't sure how to label this msg and settled for "Feature request"

![schwab](https://github.com/alexgolec/schwab-py/assets/63385373/5cbbf49e-989a-4dfc-a317-1d26df19e849)

**Comment by alexgolec** [comment]
This is a good piece of context. I'm holding off on making major modifications to the streaming code or documentation until after the official documentation is released.
