### ISSUE TITLE
Add Equity Index Symbol transition documentation 

### ISSUE THREAD

**Issue by mm0** [alexgolec/schwab-py#139]
In the transitioning from TDA documentation, there is a section for the new format of Option symbols.  It appears as though the format for equity index symbols has changed as well.

Previously, you could do a `level_one_equity_subs` for SPX and VIX indices using symbols: 

- $SPX.X
- $VIX.X

These no longer work, however the more common formats do work:

- $SPX
- $VIX

These can be confirmed by using the developer.schwab.com CUSIP search (searching by symbol for these doesn't work and didn't with TDA either) and have been confirmed by using the early mentioned `level_one_equity_subs` in schwab-py:

- $SPX cusip: 648815108
- $VIX cusip: 12497K100

**Describe the solution you'd like**
A short mention of this new symbol format to be added to the documentation.

**Describe alternatives you've considered**
Google search results will index this Issue in order to help others wondering about the same issue.

**Comment by alexgolec** [comment]
Ah, very good callout. Is it correct to say that the `.X` suffix is dropped?

**Comment by mm0** [comment]
I believe so, though it was never documented in the first place
