### ISSUE TITLE
Pydantic support request

### ISSUE THREAD

**Issue by punitarani** [alexgolec/schwab-py#153]
Are there plans to add pydantic support?

We can easily generate the models from the OpenAPI spec.
Models: https://gist.github.com/punitarani/5d12b575a7a07d850790e121fda8a65b

Pydantic model validation time is negligible.

Options Chain API call times
```
Mean: 0.69 seconds
Standard Deviation: 0.11 seconds

Min: 0.57 seconds
Max: 1.12 seconds
```

Options Chain Pydantic Validation Times:
```
Mean: 0.07 milliseconds
Standard Deviation: 0.02 milliseconds

Min: 0.04 milliseconds
Max: 0.16 milliseconds
```

**Comment by alexgolec** [comment]
Can you elaborate on what pydantic support would entail? Is the proposal to simply validate each piece of data as it comes in?

**Comment by punitarani** [comment]
Yes validation and the functions would return an object instead of the raw json response.

For example:
```python
class OptionChain(BaseModel):
    symbol: Optional[str] = None
    status: Optional[str] = None
    underlying: Optional[Underlying] = None
    strategy: Optional[Strategy] = None
    interval: Optional[float] = None
    isDelayed: Optional[bool] = None
    isIndex: Optional[bool] = None
    daysToExpiration: Optional[float] = None
    interestRate: Optional[float] = None
    underlyingPrice: Optional[float] = None
    volatility: Optional[float] = None
    callExpDateMap: Optional[Dict[str, OptionContractMap]] = None
    putExpDateMap: Optional[Dict[str, OptionContractMap]] = None
```

```python
def get_option_chain(...) -> OptionChain:
    ...
    path = '/marketdata/v1/chains'
    data = self._get_request(path, params)
    return OptionChain.model_validate(data.json())
```

**Comment by alexgolec** [comment]
I see the appeal but I'm closing this as WON'T FIX for a few reasons: 
 * The goal of this library is to simplify access to the Schwab API, and to that end it's as transparent as possible. If the API returns a JSON object, this library will return a JSON object. 
 * Maintaining this would be a nightmare. The responses can and do change at Schwab's discretion and without warning. This means any changes would result in floods of requests for support to the Discord, and would require code changes to rectify, a code release, and upgrades on the part of all users.
