### ISSUE TITLE
Lack of consistency in futures streaming handler

### ISSUE THREAD

**Issue by mm0** [alexgolec/schwab-py#168]
I believe this may have been done accidentally since other fields were modified where it _does_ make sense to have the `FUTURE` prefix.  Would it make more sense to keep this consistent with other contract/ticker types? 

`MARK_CHANGE_PERCENT` instead of `FUTURE_CHANGE_PERCENT`

https://github.com/alexgolec/schwab-py/pull/127/files#diff-b62f2adcfa00174877d0e0fe7d8bd97ae179c525f206f15a76f90c3469e2a725R1158

**Comment by alexgolec** [comment]
Unfortunately at this point the API is stable, and we're not fielding requests for potentially breaking modifications. However, I'm keeping track of these little proposals for a potential future change in which we resolve all these annoyances all at once. No concrete plans at the moment, though.
