### ISSUE TITLE
News Headlines Streaming

### ISSUE THREAD

**Issue by mm0** [alexgolec/schwab-py#169]
**Is your feature request related to a problem? Please describe.**
I didn't find any related issue, and was wondering whether Schwab API currently offers or will offer streaming of News Headlines the way TDA did.  Is this something that can be requested from them? 

**Describe the solution you'd like**
Same functionality as in tda-api https://tda-api.readthedocs.io/en/latest/streaming.html#news-headlines

**Comment by alexgolec** [comment]
Unfortunately, this stream is not available in the Schwab API, as best as we can tell.
