### ISSUE TITLE
Remove import statements referencing to tda-api library 

### ISSUE THREAD

**Issue by hn4002** [alexgolec/schwab-py#20]
Can you please fix this code - https://github.com/alexgolec/schwab-py/blob/main/schwab/orders/common.py#L367 

It has got the following code which is not allowing to create OCO orders. 
```python
     from tda.orders.generic import OrderBuilder
```
May be it is a good idea to search whole code base for "from tda" and "import tda" to find similar issues.

**Comment by alexgolec** [comment]
Fixed, thanks for pointing this out!
