### ISSUE TITLE
Verify whether date handling is correct for orders and transactions endpoints

### ISSUE THREAD

**Issue by alexgolec** [alexgolec/schwab-py#21]

**Comment by jacabreragt** [comment]
When the following code is executed:
`resp = client.get_orders_for_account(
    account_hash,
    from_entered_datetime=datetime.now() - timedelta(days=8),
    to_entered_datetime=datetime.now(),
)
assert resp.status_code == httpx.codes.OK, resp.raise_for_status()
print(resp.json())`

gives the following error:
`Traceback (most recent call last):
  File "/Users/developer/Code/python/tg/schwab/examples.py", line 61, in <module>
    resp = client.get_orders_for_account(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/developer/.pyenv/versions/tg/lib/python3.11/site-packages/schwab/client/base.py", line 258, in get_orders_for_account
    return self._get_request(path, self._make_order_query(
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/developer/.pyenv/versions/tg/lib/python3.11/site-packages/schwab/client/base.py", line 222, in _make_order_query
    'toEnteredTime': self._format_datetime(
                     ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute '_format_datetime'. Did you mean: '_format_date_as_iso'?`

**Comment by tjmorgan12** [comment]
I'm getting the same error on line 222 of base.py. 

Functions properly If modified to 'toEnteredTime': self._format_date_as_iso('to_entered_datetime', to_entered_datetime)

**Comment by alexgolec** [comment]
Looks about right now?
