### ISSUE TITLE
OCO orders not working properly, throwing 404

### ISSUE THREAD

**Issue by benjune** [alexgolec/schwab-py#23]
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

**Description of Bug**
OCO order code below throws 400. Doesn't place the order. I am able to place regular buy orders

**Code to Reproduce**
def test_OCO():
    print("Running test_OCO")
    symbol = 'RKLB'
    shares = 1
    (order1) = (OrderBuilder()
                       .set_order_strategy_type(OrderStrategyType.OCO)
                       .set_session(Session.NORMAL)
                       .set_duration(Duration.GOOD_TILL_CANCEL)
                       .set_order_type(OrderType.LIMIT)
                       .set_price(2.00)
                       .add_equity_leg(EquityInstruction.BUY, symbol, shares))
    (order2) = (OrderBuilder()
                       .set_order_strategy_type(OrderStrategyType.OCO)
                       .set_session(Session.NORMAL)
                       .set_duration(Duration.GOOD_TILL_CANCEL)
                       .set_order_type(OrderType.STOP)
                       .copy_stop_price(5.00)
                       .add_equity_leg(EquityInstruction.BUY, symbol, shares))

    order_oco = one_cancels_other(order1, order2)  # Creates a new order
    order_id = c.place_order(account_id,order_oco)
    print(f"Order ID: {order_id}")

IMPORTANT: Remember to anonymize your code. Be sure to replace API keys/Client IDs with placeholders. Also, never, ever share the contents of your token file. 

**Expected Behavior**
201, and order placed

**Actual Behavior**
400 error - doesn't place order

**Error/Exception Log, If Applicable**
PS C:\temp\python\ben> & C:/Users/benjune/AppData/Local/Microsoft/WindowsApps/python3.11.exe c:/temp/python/ben/hari_test.py
Running tests...
Running test_OCO
Order ID: <Response [400 Bad Request]>
Completed tests.

**Comment by alexgolec** [comment]
Can you please add the output of debug logging for more information? https://schwab-py.readthedocs.io/en/latest/help.html#gather-logs-for-your-bug-report

**Comment by benjune** [comment]
I got some info from another user, and it's working!
