### ISSUE TITLE
OptionSymbol not giving correct Schwab Symbology

### ISSUE THREAD

**Issue by benjune** [alexgolec/schwab-py#25]
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

**Description of Bug**
OptionSymbol not giving correct Schwab Symbology

**Code to Reproduce**
from schwab.orders.common import *
option_symbol = OptionSymbol(symbol, expiration_date, contract_type, strike_price).build()

IMPORTANT: Remember to anonymize your code. Be sure to replace API keys/Client IDs with placeholders. Also, never, ever share the contents of your token file. 

**Expected Behavior**
QQQ   240430C00432000

**Actual Behavior**
QQQ_043024C431

Still sending TDA symbology for options, not building for Schwab.

**Error/Exception Log, If Applicable**
NA

**Comment by Cfomodz** [comment]
The code you provided does not reproduce the problem. I'm looking into this currently.

**Comment by Cfomodz** [comment]
Aw, see, I knew it was wrong and your XB still got me! It's QQQ  240430C00432000 not QQQ 240430C00432000

**Comment by nkaliape** [comment]
When I attempted this to get quote of symbol - it did NOT work.

(Pdb) sy = "GOOGL_071924C195"
(Pdb) sy = "GOOGL 240719C01950000"
(Pdb) out = c.get_quote(sy)
(Pdb) out
<Response [404 Not Found]>
(Pdb) sy = "GOOGL_240719C01950000"
(Pdb) out = c.get_quote(sy)
(Pdb) out
<Response [404 Not Found]>

https://developer.schwab.com/products/trader-api--individual/details/specifications/Market%20Data%20Production
Comma separated list of symbol(s) to look up a quote

Example : MRAD,EATOF,EBIZ,AAPL,BAC,AAAHX,AAAIX,$DJI,$SPX,MVEN,SOBS,TOITF,CNSWF,AMZN 230317C01360000,DJX 231215C00290000,/ESH23,./ADUF23C0.55,AUD/CAD

Which one is correct? how to go about it? Kindly advise


Name | Description
-- | --
symbolsstring(query) | Comma separated list of symbol(s) to look up a quoteExample : MRAD,EATOF,EBIZ,AAPL,BAC,AAAHX,AAAIX,$DJI,$SPX,MVEN,SOBS,TOITF,CNSWF,AMZN 230317C01360000,DJX 231215C00290000,/ESH23,./ADUF23C0.55,AUD/CAD


Name | Description
-- | --
symbolsstring(query) | Comma separated list of symbol(s) to look up a quoteExample : MRAD,EATOF,EBIZ,AAPL,BAC,AAAHX,AAAIX,$DJI,$SPX,MVEN,SOBS,TOITF,CNSWF,AMZN 230317C01360000,DJX 231215C00290000,/ESH23,./ADUF23C0.55,AUD/CAD

**Comment by nkaliape** [comment]
sy = "SPY,GOOGL 240719C00195000"
(Pdb) out = c.get_quotes(sy)
(Pdb) out.json()

# above API worked
