### ISSUE TITLE
unable to locate schwab-generate-token.py

### ISSUE THREAD

**Issue by nkaliape** [alexgolec/schwab-py#40]
Unable to locate the schwab-generate-token.py
Can we please have sample code and also a video walk through? that can help big way.

**Comment by TamirP** [comment]
had same issue, but finally succeeded in the *schwab.auth.client_from_manual_flow()* , had to correct line #332 in auth.py replacing __prompt__ to __input__ to allow the input prompt to work (maybe old python code). and then just go through the login process on a browser approving all the required text and copying the resulting redirect URL.
