### ISSUE TITLE
Does the schwab API support more order types than just equities and options? 

### ISSUE THREAD

**Issue by alexgolec** [alexgolec/schwab-py#5]
Might want to create templates for them if so

**Comment by Cfomodz** [comment]
Per spec:

Order types: [ MARKET, LIMIT, STOP, STOP_LIMIT, TRAILING_STOP, CABINET, NON_MARKETABLE, MARKET_ON_CLOSE, EXERCISE, TRAILING_STOP_LIMIT, NET_DEBIT, NET_CREDIT, NET_ZERO, LIMIT_ON_CLOSE ]

Complex order types: [ COVERED, VERTICAL, BACK_RATIO, CALENDAR, DIAGONAL, STRADDLE, STRANGLE, COLLAR_SYNTHETIC, BUTTERFLY, CONDOR, IRON_CONDOR, VERTICAL_ROLL, COLLAR_WITH_STOCK, DOUBLE_DIAGONAL, UNBALANCED_BUTTERFLY, UNBALANCED_CONDOR, UNBALANCED_IRON_CONDOR, UNBALANCED_VERTICAL_ROLL, MUTUAL_FUND_SWAP, CUSTOM ]

Advanced order types:
[ OTO, OCO, OTOCO, OT2OCO, OT3OCO, BLAST_ALL, OTA, PAIR ]

Order strategy types:
[ SINGLE, CANCEL, RECALL, PAIR, FLATTEN, TWO_DAY_SWAP, BLAST_ALL, OCO, TRIGGER ]

**Comment by alexgolec** [comment]
No, this is a good listing. Based on this it looks like it supports some rather complex orders, but no futures or forex. Closing this now.
