### ISSUE TITLE
Constructing OptionSymbol with symbol longer than six characters should not be allowed

### ISSUE THREAD

**Issue by s-maheshbabu** [alexgolec/schwab-py#58]
**Description of Bug**
We are currently able to create OptionSymbols like `MOCKTIC221231C00165000`. These option symbols will then throw errors further down the lane when users try to use the symbol and those errors can be inaccurate. 

For example, the above example will render even though the underlying root cause is a ticker that is too long. 

> expiration date must follow format [two digit year][Month with leading zero][Day with leading zero]

**Code to Reproduce**
`OptionSymbol("MOCKTIC", "221231", "C", "165").build()`

**Expected Behavior**
Throw an error at creation saying tickers cannot be longer than six characters long.

**Actual Behavior**
OptionSymbol gets created successfully.

**Comment by alexgolec** [comment]
This is working as intended. The options symbol generator/parser is not meant to be a validator.

**Comment by s-maheshbabu** [comment]
```
expiration_date must be a string with format %y%m%d ' +
                '(e.g. 240614) or one of datetime.date or ' +
                'datetime.datetime
```
                
```
'strike price must be a string representing a positive ' +
                'float'
```
                
```
Contract type must be one of \'C\', \'CALL\', \'P\' or \'PUT\'
```

```
option symbol must have format ' +
            '[Underlying left justified with spaces to 6 positions][Expiration][P/C][Strike]
```

Why do we have all these validations in OptionSymbol `init` and `parse` functions then? Just trying to understand what the rationale is behind validating some parts of the option symbol but not others. 

In the interest of consistency and failing-fast, happy to add the validations myself.
