### ISSUE TITLE
Expiration dates without leading zeroes should not be parsed successfully into OptionSymbol

### ISSUE THREAD

**Issue by s-maheshbabu** [alexgolec/schwab-py#59]
**Description of Bug**
`GOOG122223C145` is being successfully parsed into a OptionSymbol. Since the first six characters are the ticker, the expiration date here is '2223'.

The documentation also says - 

> expiration date must follow format [two digit year][Month with leading zero][Day with leading zero]

So, GOOG122223C145 should not parse into a valid OptionSymbol.

**Expected Behavior**
Trying to parse `GOOG122223C145` into OptionSymbol raises ValueError.

**Actual Behavior**
`GOOG122223C145` gets parsed into a valid OptionSymbol.

**Comment by alexgolec** [comment]
The parsing functionality is intended to parse symbols produced by the options chain endpoints. It is not a validator.
