### ISSUE TITLE
easy_client is not working as expected

### ISSUE THREAD

**Issue by gsafro** [alexgolec/schwab-py#63]
Environment: Linux (Amazon Linux 2)
API version: schwab-py 0.0.0a28
Python version: 3.8.16

**Description of Bug**
1) easy_client() does not refresh the access token.
2) I can successfully create token.pickle, but it contains only access_token. The refresh_token is not created.

**Code to Reproduce**
I can successfully create token.pickle by
import schwab
token_path='.../token.pickle'
schwab.auth.client_from_manual_flow(api_key=..., app_secret=..., callback_url='https://127.0.0.1', token_path=token_path, asyncio=False, token_write_func=None, enforce_enums=False)

After that I can successfully use easy_client() to access my schwab account during the first hour:

from schwab.auth import easy_client
import json
token_path='.../token.pickle'
c = easy_client(api_key=..., app_secret=..., callback_url='https://127.0.0.1', token_path=token_path)
syms = ['AAPL']
raw_resp = c.get_quotes(syms)
resp = raw_resp.json()
print(resp)

But in 1 hour the access_token is expired and the connectivity does not work anymore.

**Expected Behavior**
1) easy_client() automatically refreshes access_token in the token.pickle file
2) client_from_manual_flow() function adds both access_token and refresh_token to the token.pickle file

**Actual Behavior**
1) access_token is expiring in 1 hour
2) refresh_token is not added to the token.pickle file

**Error/Exception Log, If Applicable**
  File "./test_client.py", line 23, in <module>
    raw_resp = client.get_quotes(syms)
  File "/usr/local/lib/python3.8/site-packages/schwab/client/base.py", line 484, in get_quotes
    return self._get_request(path, params)
  File "/usr/local/lib/python3.8/site-packages/schwab/client/synchronous.py", line 19, in _get_request
    resp = self.session.get(dest, params=params)
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1054, in get
    return self.request(
  File "/usr/local/lib/python3.8/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 202, in request
    raise InvalidTokenError()
authlib.integrations.base_client.errors.InvalidTokenError: token_invalid:

**Comment by alexgolec** [comment]
https://schwab-py.readthedocs.io/en/latest/tda-transition.html#no-more-client-from-login-flow-or-easy-client

**Comment by gsafro** [comment]
Thanks for help!
