### ISSUE TITLE
Streaming field names for timestamps should be changed

### ISSUE THREAD

**Issue by hn4002** [alexgolec/schwab-py#81]
In the tda-api, we had names like "TRADE_TIME_IN_LONG", "REGULAR_MARKET_TRADE_TIME_IN_LONG", etc.
In the latest schwab-py, they have been named as "TRADE_TIME_MILLIS", "REGULAR_MARKET_TRADE_MILLIS", etc. 

The names should be backward compatible where ever possible. If Schwab streaming stopped streaming a particular field, then that is fine. But if Schwab streaming is providing the same field which was there in TDA streaming, then the name of the field should be maintained. I don't see any advantage of changing these field names. Based on my code base, I can see that these field names have been used to access the values in the returned data at multiple places in multiple files and these name changes will create confusion for the users.

**Comment by alexgolec** [comment]
Note that while this library is heavily inspired by/based on the old one, backwards compatibility is not an explicit goal. Some amounts of migration will be necessary.
